plugins:
  - rubocop-md
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.6.0
  NewCops: enable
  Exclude:
    - .git/**/*
    - vendor/bundle/**/*

Layout/IndentationConsistency:
  Exclude:
    - README.md

Layout/InitialIndentation:
  Exclude:
    - README.md

Layout/LineLength:
  Max: 120
  Exclude:
    - lib/cloudflare/turnstile/rails/constants/*.rb
    - cloudflare-turnstile-rails.gemspec

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/MethodLength:
  Max: 12

Minitest/MultipleAssertions:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Exclude:
    - README.md

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

